# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
