# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
