# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180828_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_second',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
